blog/urls.py
from . import views
from django.urls import path


app_name = "blog"
urlpatterns = [
    path('', views.ArticleList.as_view(), name='posts'),
    path('<slug:slug>/', views.ArticleDetail.as_view(), name='post'),
    path('tag/<slug:slug>/', views.TaggedListView.as_view(), name="tagged"),
]

django-divio-blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('blog.urls')),

]

# Serving the media files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

quickstart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _
from easy_thumbnails.fields import ThumbnailerImageField
from taggit.managers import TaggableManager
from tinymce.models import HTMLField


class Article(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name=_('Title'))
    title_de = models.CharField(max_length=200, unique=True, verbose_name=_('Title German'))
    slug = models.SlugField(max_length=200, unique=True, verbose_name=_('Slug'))
    slug_de = models.SlugField(max_length=200, unique=True, verbose_name=_('Slug German'))
    thumbnail = ThumbnailerImageField(blank=True, verbose_name=_('Thumbnail'))
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Author'))
    created_on = models.DateTimeField(auto_now_add=True, verbose_name=_('Created on'))
    content = HTMLField(verbose_name=_('Content'))
    content_de = HTMLField(verbose_name=_('Content German'))
    tags = TaggableManager(verbose_name=_('Tags'))

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from taggit.models import Tag

from .models import Article


class ArticleList(ListView):
    queryset = Article.objects.all().order_by('-created_on')
    template_name = 'posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        common_tags = Article.tags.most_common()[:4]
        context["common_tags"] = common_tags
        return context


class ArticleDetail(DetailView):
    model = Article
    template_name = 'post.html'


class TaggedListView(ArticleList, ListView):
    view_url_name = "djangocms_blog:posts-tagged"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(tags__slug=self.kwargs["slug"])

    def get_context_data(self, **kwargs):
        kwargs["tagged_entries"] = self.kwargs.get("slug") if "slug" in self.kwargs else None
        context = super().get_context_data(**kwargs)
        return context

blog/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- will be replaced with meta content -->
    {% block metatags %}{% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <style>
        html, body {
            height: 100%;
        }

        body {
            font-family: sans-serif;
            font-size: 18px;
            background-color: #fdfdfd;
            display: flex;
            flex-direction: column;
        }

        #nofooter {
            flex: 1 0 auto;
        }

        darkbtn {
            color: #66ff99;
        }

        .dark-mode {
            background-color: black;
            color: white;
        }

        #foot {
            flex-shrink: 0;
            font-family: sans-serif;
            background-color: #BDFFD3;
            color: #00308F;
            bottom: 0px;
            width: 100%;
        }

        .card-group, .card, .card-footer, .card-body {
            border: none;
        }
    </style>
</head>
<body>
<div id="bodydiv">
    <div id="nofooter">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="topnav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:posts' %}">
                    what.</a>
                <div class="nav justify-content-end">
                    <div class="d-inline">
                        <a class="nav-link text-black font-weight-bold"
                           href="{% url 'blog:posts' %}">{% trans "Articles" %}</a>
                    </div>
                    <div class="d-inline">
                        <!-- dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="/" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">{% trans "Language" %}</a>
                            <form action="{% url 'set_language' %}" method="post" id="lang_form">{% csrf_token %}
                                <input name="next" type="hidden" value="{{ redirect_to }}">
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    {% get_current_language as LANGUAGE_CODE %}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                        <li>
                                            <button type="submit" name="language" value="{{ language.code }}"
                                                    class="{% if language.code == LANGUAGE_CODE %}selected{% else %}demo-text-black{% endif %} dropdown-item">
                                                {{ language.name_local }}
                                            </button>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </form>
                            </a>
                        </li>
                        <!--/ dropdown -->
                    </div>

                </div>

            </div>
        </nav>
        <!-- will be replaced with post content -->
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="footer" id="foot">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">


                    <p>Copyright © what.</p>


                    <div class="nav justify-content-center" id="navfooter">
                        <span><a class="nav-link text-black font-weight-bold" href="#">{% trans "About" %}</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#">{% trans "Privacy" %}</a></span>
                        <span><a class="nav-link text-black font-weight-bold" href="#">{% trans "Terms" %}</a></span>
                    </div>
                </div>
            </nav>
        </div>
    </footer>
</div>
</body>
</html>

blog/templates/post.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% get_current_language as LANGUAGE_CODE %}
{% block metatags %}
    {% if LANGUAGE_CODE == 'de' %}
        <title>{{ object.title_de }}</title>
    {% elif object.title %}
        <title>{{ object.title }}</title>
    {% endif %}
<meta property="og:title" content="{{ object.title }}">
<meta property="og:site_name" content="what.">
<meta property="og:url" content="{% url 'blog:post' object.slug %}">
<meta property="og:type" content="article">
{% endblock %}
{% block content %}
<style type="text/css">
#container img {
border-radius: 29px;
width: 100%;
height: 360px;
opacity: 0.7;
align-content: center;
}
#container img {
opacity: 1.0; }
a {text-align: center; text-decoration: none;}
.jumbotron {
    padding: 0;
}
</style>
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;">
{% thumbnail object.thumbnail 1500x400 upscale crop as thumb %}
                                    <img src="{{ thumb|data_uri }}" style="width: 100%;">
</header>
<div class="container">
<div class="row">
<div class="col-md-6 left">
		<h1 class="card-title">{% block title %}
            {% if LANGUAGE_CODE == 'de' %}
                {{ object.title_de }}
            {% elif object.title %}
                {{ object.title }}
            {% endif %}
        {% endblock title %}</h1>
		<p class=" text-muted">{{ object.author.first_name }} {{ object.author.last_name }} |{{ object.created_on }}</p>

		{% for tag in object.tags.all %}
            <a href="#" class="badge badge-info" >{{ tag }}</a>
        {% endfor %}




		<p class="card-text">
            {% if LANGUAGE_CODE == 'de' %}
                {{ object.content_de | safe }}
            {% elif object.content %}
                {{ object.content | safe }}
            {% endif %}
        </p>



	</div>
	</div>
	</div>
{% endblock content %}

blog/templates/posts.html
{% extends "base.html" %}
{% load i18n %}
{% load thumbnail %}
{% get_current_language as LANGUAGE_CODE %}
{% block metatags %}
<title>{%  trans "Home" %} | what.</title>
<meta property="og:title" content="what.">
<meta property="og:site_name" content="what.">
<meta property="og:url" content="https://what.digital">
<meta property="og:type" content="website">
{% endblock %}
{% block content %}
<style type="text/css">
	body {
	font-family: 'Raleway', sans-serif;}
	.head_text {
		color: white;
	}
.h1, h4 {
font-family: 'Raleway', sans-serif;
}
#mainhome {
text-align: center; }
</style>
<header class="jumbotron" style="background-color: #BDFFD3; color: #00308F;">
	<div class="container">
	    <p class="h1">{% blocktranslate %}Welcome to{% endblocktranslate %} <strong>what.</strong></p>
    </div>
</header>
<div class="container pt-5">
            {% if tagged_entries %}
                <div class="d-inline">
                    <a href="#" class="badge badge-success">{{tagged_entries}}</a>
                    <a class="close" style="float:none" href="{% url 'blog:posts'%}">x</a>
                </div>
            {% else %}
                <p>{% blocktranslate %}Common Tags{% endblocktranslate %}:
                    {% for mt in common_tags %}
                        <a href="{% url 'blog:tagged' mt.slug %}" class="badge badge-success">{{mt}}</a>
                    {% endfor %}
                </p>
            {% endif %}

            <div class="row mb-2 posts">
                    {% for post in object_list %}
                    <div class="col-md-6">
                        <div class="cards">
                            <div class="row no-gutters border rounded  flex-md-row mb-4 shadow-sm h-md-250">
                                <div class="col p-4 d-flex flex-column position-static">
                                    <h3 class="my-1"><a href="{% url 'blog:post' post.slug %}">
                                        {% if LANGUAGE_CODE == 'de' %}
                                            {{ post.title_de }}
                                        {% elif post.title %}
                                            {{ post.title }}
                                        {% endif %}
                                        </a></h3>
                                    <div style="display:flex">
                                        {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:tagged' tag.slug %}" class="mr-1 badge badge-info">#{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                    <img src="{{ post.thumbnail.avatar.url }}" alt="" />
                                {% thumbnail post.thumbnail 500x500 crop as thumb %}
                                    <img src="{{ thumb|data_uri }}">
                                    <p class="mb-auto">
                                        {% if LANGUAGE_CODE == 'de' %}
                                            {{post.content_de |truncatewords_html:100|safe}}
                                        {% elif post.content %}
                                            {{post.content |truncatewords_html:100|safe}}
                                        {% endif %}
                                    </p>
                                    <p class="mb-auto text-muted">{{post.created_on}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
            </div>
        </div>

{%endblock%}